### ISSUE TITLE
Make legends not spawn on AFK players

### ISSUE THREAD

**Issue by dvos1998** [NebulaMC-GG/Suggestions#101]
As it frustrates alot of players when a legend spawns on an afk player (and it will almost always despawn on them or they disconnect for being AFK for to long), it would be nice to never have a legendary spawn on an afk player.

This might be done by having the spawn thing revere to the afkcheck list to see who it must not spawn on.

**Comment by HackuJacku** [comment]
We are working on stopping Pokémon spawning for players who are considered as AFK :)
