### ISSUE TITLE
the wiki command 

### ISSUE THREAD

**Issue by DlNGY6** [NebulaMC-GG/Suggestions#103]
the /wiki command should be expanded upon by allowing you to do /wiki [biome] either enter their and it will tell you all the pokemon spawning in that biome or continue by adding [type] or [time] or [legendary]. their could be a command for items as well but not needed as much as most tell you anyway.

**Comment by HackuJacku** [comment]
The `/wiki` command is getting a complete overhaul as part of Pixelmon 9.0.9. We won't be updating to Pixelmon 9.0.9 as it has critical gamebreaking bugs, causing it to be unplayable - once 9.0.10 is released, we'll update to that :)
