### ISSUE TITLE
Add back chest shops if possible.

### ISSUE THREAD

**Issue by StrideMate** [NebulaMC-GG/Suggestions#104]
It would be cool to even without /playershops as a command, To just be able to build a mall or shop and be able to tp people to that area and they'll still be able to buy through the chest shops like back in 1.12. I don't know if you'd be able to add it in 1.16 but It would be a nice addition If the server had it. Thank you :D

**Comment by HackuJacku** [comment]
As per our latest update in our `/discord` announced, this has been re-introduced :)
