### ISSUE TITLE
Legend spawn modifications

### ISSUE THREAD

**Issue by CaptainTCovenant** [NebulaMC-GG/Suggestions#108]
While camping Darkrai on a New Moon in Dark Forest Hills, I had come to realize how many legends spawn in that biome at night, compared to day. 
I suggest removing or changing the time Cobalion spawns at, since it spawns in the same biomes at the same time as another one of the Swords of Justice trio, Terrakion.  

Also, with Mewtwo being obtainable via shrines, I suggest removing it as a possible wild spawn, though this one is less likely to happen. Since someone could argue they would rather hunt a wild Mewtwo than hunt a mew and collect money to get Mewtwo.

**Comment by CenizaRey** [comment]
I will work on this today. Just so you know, Mewtwo was removed from Wild Spawns last night.
