### ISSUE TITLE
Poipole Invasion instead of Naganadel

### ISSUE THREAD

**Issue by EzelBerbier** [NebulaMC-GG/Suggestions#109]
Would be nice if instead of Naganadel spawning in a Invasion on Highrift, would be Poipole the one who spawned there. Make only Naganadel availabe makes Poipole impossible to get, after all its the pre evolution of it and u need it for dex, and in the old map was Poipole the one that appeared there instead Nagandel, for obvious reasons.

**Comment by EzelBerbier** [comment]
I understood wrong the announcement, Poipole spawn and Naganadel is from raid, so my suggestion does not have any sense. Sadly i can't close it or delete, so sorry in advance.

**Comment by Oisin-Hearne** [comment]
This change has been implemented, as it would make more sense for Poipole to be more common (In the dens) than Naganadel. Thanks for the suggestion!
