### ISSUE TITLE
invasion rework idea along with custome texture idea for ultrabeast

### ISSUE THREAD

**Issue by Crimlatheloli** [NebulaMC-GG/Suggestions#110]
rework the invasion to spawn custom textured ultrabeast and have regular ubs spawn like they did before and as for the special texture idea since ubs came in a generation with the space themed legends aka cosmog being a nebula cosmoem being the core of a start lunala being the beast of the moon solgaleo being hte sun lion and necrozma being a dead star/ black hole and ultra necrozma being a supernova and the fact that ultra beasts come from ultra **SPACE** you could have a custom texture of space themed ultrabeasts like pheromosa being nebula themed or guzzlord being like a wormhole themed one

**Comment by Oisin-Hearne** [comment]
I like this idea! I'll be looking into making some concepts for them. Thank you for the suggestion :D!
