### ISSUE TITLE
Legendaries Suggestion

### ISSUE THREAD

**Issue by innqmorato** [NebulaMC-GG/Suggestions#111]
In the last times legendaries, at least on orion, have been like 4 to 6 a day,i think that's pretty a low number for a server with at least 15+ players often, i would like to suggest something to be done at legendaries spawns, at least in the meanwhile for quests, beacuse, talking for what's my situation, i have bad rng and i've got 3 legendaries in the last 3 weeks, i know that's basically luck but for pepole who want to achieve origin that's really a big issue, considering school and work for a lot of gamers. And yea, of course, legendary spawning should not be a common thing, but i think it souldn't be also the rarest, considering that some leggies are lost cause of afk people. So i would suggest like a rates increasing or something like that because without quests, people in my situation with really bad rng have literally nothing to do atm in the server except building.

**Comment by Rasgnarok** [comment]
AFK players now are ignored by the legendary spawner, thank you for the ticket!
