### ISSUE TITLE
Adventure Map Breeding 

### ISSUE THREAD

**Issue by ThirstyMichael** [NebulaMC-GG/Suggestions#112]
With the change to the breeding mechanic, blocks are no longer tied to the player, and since you only need one in place of having multiple could be added to locations around the adventure map for public use in the same way that max power enchanting tables are. And if the adventure map gyms are meant as an entry to competitive battling, then it only makes sense to have a Nursery to act as a tutorial area at the minimum.

**Comment by CenizaRey** [comment]
All major cities now have a daycare block in their pokecenter. Thanks for the suggestion! Closing.
