### ISSUE TITLE
dodgeball with tridents Game Idea

### ISSUE THREAD

**Issue by killercreechan** [NebulaMC-GG/Suggestions#113]
a normal game of dodgeball with tridents where there on 1 block and if they get hit there eliminated by falling off the block last team alive wins and its tournament style teams face each other and each winner moves up to face winners of another round then the final team face against each other for the ultimate winner. You guys can change it up if needed for it to work just a suggestion

**Comment by PenginKami** [comment]
I think this is a cool idea, but giving everyone tridents might be bad. Maybe have two teams, and place all the players of each team on a seperate row of blicks. Give a random player on each team a snowball every 10 seconds to throw at the other team and hope to knock them off, whilst those who don't get a snowball are trying to dodge. Would definitely be fun to watch and play.

**Comment by killercreechan** [comment]
that works too i thought of this while playing dodge the trident with a friend xD

**Comment by Malphir** [comment]
An alternative for this is using crossbows with spectral arrows (the ones that make you glow when you get hit).

**Comment by killercreechan** [comment]
ooo good idea too

**Comment by Chunkkss** [comment]
This would be something to bring up to wizards, or leave on your wizard application!

Thanks for the suggestion
