### ISSUE TITLE
Add Nature's Compass from official Pixelmon Modpack

### ISSUE THREAD

**Issue by KuwuroUsagi** [NebulaMC-GG/Suggestions#115]
Nature's Compass is in the official pixelmon modpack, it's a great accompanying mod for pixelmon because it allows for searching for specific biomes which is an integral part of the pixelmon system for finding pokemon. It would prevent rtp spam meta as well and increase playtime of players and population count by retaining playercount because players would have a direction to go instead of using a low cooldown random teleport command.

There are other mods for finding structures, or adding more biomes and variants of wood/trees, etc

The biomes might involve a new map which wouldn't be ideal, so there's no need for BYG.

Explorer's Compass is similar to Nature's Compass, but allows for searching for generated structures, a cool thought but if not desired, wouldn't be missed too much I would think.

**Comment by PenginKami** [comment]
If they can find a lag free- efficient way to add a compass that does this ingame, it'd be good. This has been suggested tons in different forms, but there's issues with most solutions ending up worse for server performance then rtp spam. I think this is a solution for us to solve in the end. Maybe we need to make a link to a list of every biome and their coords.
Another idea that I still like a ton is having an online map, would be a cool thing to look at and it'd be a way to find places to build, and also help find biomes.

**Comment by KuwuroUsagi** [comment]
> If they can find a lag free- efficient way to add a compass that does this ingame

Nature's Compass is an incredibly lightweight mod and is already in the official pixelmon modpack (Coincidentally how I found NebulaMC)

All it would require is putting it in the server, and it'd function perfectly, it's not as though it does anything serverload-wise. Instead of rtp spam we might see people flying or walking or riding mons more or using elytras if it's very far.

**Comment by CenizaRey** [comment]
This has the potential to alienate many of our players who don't use the official pixelmon modpack, or perhaps self-install their mods. If they see they don't have the right mods for our server, they will simply just find another one that doesn't carry Nature's Compass. We want to keep our modlist as lightweight as possible by only having one mandatory mod - Pixelmon. Thanks for the suggestion! Closing
