### ISSUE TITLE
Rebrand and Advertise Modpack

### ISSUE THREAD

**Issue by KuwuroUsagi** [NebulaMC-GG/Suggestions#116]
I had no idea there was an official Nebula modpack until I had already joined the server. It's not advertised on the website, or in the discord. Once found (via in-game) the modpack doesn't even have any references to NebulaMC aside from a resource pack hidden in the solder file list, and the discord that doesn't say it's the NebulaMC official discord anywhere on the modpack page.

Apex Pixelmon doesn't seem related whatsoever to NebulaMC and it's a missed opportunity to streamline the process for players to find and play on the server.

**Comment by PenginKami** [comment]
honestly im confused whether apex pixelmon is affiliated at all with nebula

**Comment by CenizaRey** [comment]
Nebula controls Apex Pixelmon, that’s why my name is attached to all the patch updates in the launcher

**Comment by Chunkkss** [comment]
This is advertised in the Intro page in discord!

Thanks for the suggestion.
