### ISSUE TITLE
Label Merchants in Market

### ISSUE THREAD

**Issue by KuwuroUsagi** [NebulaMC-GG/Suggestions#117]
With so many different NPCs in the Market at spawn, it's nigh impossible to remember who sells what trying to remember simply just the skin of the npc.

It would be a great quality-of-life update to be able to differentiate them somehow, whether it be naming them certain types of merchants or grouping them with signs or item frames that loosely describe what they sell. Like Pokemart, TM/HM Salesman, Construction Mart or w/e. Would save a lot of headaches for players trying to find what they need.

**Comment by PenginKami** [comment]
Make my life so much easier, I am always running around like a headless farfetch'd trying to find the right npc lol

**Comment by KittyKatzyn** [comment]
This has been completed!  Thank you for the suggestion :)
