### ISSUE TITLE
Remove unfinished quests in Adventure

### ISSUE THREAD

**Issue by KuwuroUsagi** [NebulaMC-GG/Suggestions#118]
At this point, quests are not implemented, but their husks and infrastructure are still in the world.

It's very confusing and frustrating for players to think there's a quest and work towards it, only to find out that it was all for naught. 
(-196, -125, Adventure, Orion)
![image](https://user-images.githubusercontent.com/6632311/192124512-460a8c10-360b-4044-abc4-02af5eabd385.png)

Areas similar to this should be implemented when the quest actually functions, as just outside looking in, this looks like an obvious quest hook for players to participate in.

**Comment by CenizaRey** [comment]
We plan on re-adding quests in the foreseeable future (as soon as it becomes possible). Removing the infrastructure for quests we plan to readd would set us back weeks, and is unviable. Thanks for the suggestion!
