### ISSUE TITLE
Server Resource Pack

### ISSUE THREAD

**Issue by KuwuroUsagi** [NebulaMC-GG/Suggestions#121]
Having an automatic download upon joining the server so that the resource pack is more easily available to players would be a great quality-of-life addition.

**Comment by CenizaRey** [comment]
We attempted this when Nebula first came into being in June of this year. It produced an unbearable load on the clients of users with weaker PCs. There exists no workaround or alternative.

In our attempt to remedy this, the link to the latest Resource Pack is in routine ingame announcements, accessible via /resourcepack, in the “intro” channel on the Discord, and comes pre-loaded with the Apex Pixelmon modpack on the Technic Launcher. We feel this is sufficient. Thanks for the suggestion!
