### ISSUE TITLE
Vote Party

### ISSUE THREAD

**Issue by KuwuroUsagi** [NebulaMC-GG/Suggestions#123]
It's insane that the vote party function only awards the people logged in to the server when the final vote is registered. Players can contribute quite heavily over the passing days by repeatedly voting, and there is no way for them to accurately track or partake in the reward for the community coming together to reach the vote goal. Everyone who voted should be rewarded for contributing to the milestone, or else it's worthless.

**Comment by Chunkkss** [comment]
Duplicate Ticket, closing this one. Suggestion forwarded.
