### ISSUE TITLE
flying legends speed reduction

### ISSUE THREAD

**Issue by killercreechan** [NebulaMC-GG/Suggestions#124]
i have noticed some flying legends like latios and latias's fly speed hard to keep up with early on and and if you dont notice it and cant keep up you end up losing them because all that have spawned i have noticed have gotten away and not caught so i suggest all flying legends flying speed slowed down so players can keep up with them without needing the /fly command.

**Comment by Rasgnarok** [comment]
We need to know which legendaries are too fast, can you please file it here when you confirm one: https://github.com/NebulaMC-GG/Bugs-and-Issues/issues
