### ISSUE TITLE
Transfer Tutors

### ISSUE THREAD

**Issue by Fatal-Horizon** [NebulaMC-GG/Suggestions#126]
There are many moves that can only be taught to pokemon through a Transfer Tutor specifically. I'm not sure if they are already planned to be added to a city like Ione for the Move Tutors, but if they are not already I believe it would benefit players greatly if more were added since there is only one so far and it does not teach the full list. Limiting many move lists from pokemon as well as many builds that people can create. If adding more of them wouldn't work out then I also think for the one Transfer Tutor that is currently present, could possibly have a weekly rotating move list for players to check. this can mean some higher tier abilities can have rarity, thus making a little game out of it to check the NPC weekly. Hope this suggestion finds some promise c: tysm

**Comment by Chunkkss** [comment]
I believe there was a pixelmon issue with transfer tutors that has been fixed. Should be able to access the full list, and there are plans to have tutors in each city. 

Thanks for the suggestion!
