### ISSUE TITLE
Ways to get cosmetic commands

### ISSUE THREAD

**Issue by PenginKami** [NebulaMC-GG/Suggestions#127]
Hi, so I've been having a first world problem recently.
I've got omen on orion and I take full use of the cosmetics, It makes me happy to have my in game username as it is.
recently I've gotten bored of orion... Soo I've decided I wanna play either atlas or titan, 

I join in excited to play, and then I type in chat and then it hits me, my username and cosmetics are gone, I'm fine with the commands not being there since they make you "stronger" and thats what you get with the ranks you pay for but the cosmetics really hurts me, I can't play without wanting to instantly switch back to orion, its making it impossible for me to enjoy myself and play with others when I feel forced to play on orion just because I spent money on it.
obviously im self aware enough to know this is really stupid of a problem, and "oh no the person who spent $300 on a rank is complaining they can't have a colorful username" but honestly my feelings and annoyance at it is kinda overwriting all embarrassment.

I'd like to suggest ways for people to somehow get cosmetics. Maybe a /nick token from events for example, just some sort of way where I can log on to titan or atlas and have my colorful fancy username still without spending an extra $300. 

idea list:

Idea 1: Cosmetic tokens for players, I think that getting these from the cosmetic crates or events would be nice, just allowing you to maybe use the cosmetic commands for a week and then expiring for example, or maybe a one time use ask staff.

Idea 2: Make it so cosmetics with ranks are universal (so apply to all servers), or maybe the cosmetic commands like /nick automatically carry over to other servers with fancy magic.

Idea 3: Make it so cosmetics can be sold separately in the store for significantly cheaper...

Im honestly unsure why I feel so strongly about my username just being different, but its causing me way more stress then it should...

anyway yep thats the suggestion

**Comment by CenizaRey** [comment]
Permission nodes don't really work like this. In order for you to keep your cosmetics on a server you don't have your donor rank on, we would have to create an entirely separate rank that is given to people who have donated on other servers - which defeats the point of not having the ranks carry over in the first place. 

Cosmetics are things that can represent one's status and place in the community, it would be unusual to other players to have their server be dominated by big fancy coloured bold lettering from someone they have never seen playing on their server until now, they could be mistaken for a staff member, for example.

I feel the fact you're finding it "impossible" to play on other servers is ultimately an ego thing. If you truly want to separate yourself from the general playerbase without donating for an entire rank with the permissions to do so, you can grind for flairs in the vote or cosmetic crate. Or if you're looking for a faster option for a lower price, you can purchase cosmetic keys specifically for these bold, flashy flairs. 

Closing for now, thanks for the suggestion!

**Comment by PenginKami** [comment]
I apologize if commenting reopens it- this was made before we had tags, and honestly I got over it pretty quickly- definitely an ego thing lol
