### ISSUE TITLE
Hidden ability tracker is over powered

### ISSUE THREAD

**Issue by PenginKami** [NebulaMC-GG/Suggestions#131]
I think that hidden ability being tracked in poketracker might be bad,

unless shinies or legendaries, you can't just tell they're a shiny or legendary by looking at it.

So poketracking hidden ability mons might make it significantly easier to find hidden abilities, as it means you don't have to check for the hidden ability of the mon you're hunting.

Like, TONS of hidden ability mons spawn all the time, but you will only find the ones you're actively checking. but now you can just use poketracker to have zero risk of despawning a hidden ability mon you didn't know was even there without it

Solutions:

Make it so ACTIVE Ha mons don't display

Makes it funnier when people realize the mon they were hunting despawned, and it also allows others to see what was caught

A way to keep it would be to just tell you in chat that a Hidden ability mon spawned on you, so now you gotta figure out which mon is Hidden ability before it despawns. 
![2022-10-16_14 49 47](https://user-images.githubusercontent.com/96862959/196019000-1db3f165-aa46-4ad3-895e-7d578146fdf4.png)
![2022-10-16_15 00 29](https://user-images.githubusercontent.com/96862959/196019002-36b1e5b2-f4d4-4318-a17f-1e49e246f75b.png)
Like, hidden ability mons are super common. What makes them rare is not knowing they're even there in the first place.

**Comment by Malphir** [comment]
Personally I don't mind this bein added as a feature. HA hunts get exhausting and you still need Trace to verify if it's the right mon. This is my view as the person that has hunted the most HAs on Titan prior to this feature. I do not mind if others can find them easier because of this. It'll still be a slog to get them, but it's less of a pain now.

**Comment by PenginKami** [comment]
I disagree.
![2022-10-16_18 29 32](https://user-images.githubusercontent.com/96862959/196026120-905ac2ae-d938-4ce0-9057-0d0d270c1964.png)

![2022-10-16_18 29 22](https://user-images.githubusercontent.com/96862959/196026118-ce6c2823-9462-44b8-a672-c80654e8d173.png)

I have 3 hours on titan, and in this 30 minute session my basically brand new **with no stuff** account has gotten multiple ha's
I'd be able to get more if I had efficient mons for catching, but this is literally with level 10's and 20's no lures, and in the adventure map without a rank with /fly and homes to efficiently respawn stuff.

I'm having more difficulty with /hunts then getting ha's lol

Edit: add a ha foongus to the list :p

I think what's best is definitely if it just tells you theres an active Ha mon on you as the player specifically, but not what it is.
