### ISSUE TITLE
Add some emoji's! (little emoji addition list)

### ISSUE THREAD

**Issue by PenginKami** [NebulaMC-GG/Suggestions#133]
:sob; which looks like 😭 
;-;  would also maybe have an emoji similar or even the same to 😭 

:bruh: which entails the feeling of bruh 🗿 🐟 

:thumbsup; 👍  emoji
:thumbsdown; 👎 emoji

Some sort of lol/rofl/lmfao/lmao/whatother acronyms we have for laughing emoji 🤣 

:confusion: which displays absolute confusion, I am unsure what it looks like but it looks like me when someone says something and my brain hurts

And last of all some sort of happy pog emoji idk

Another thing to mention is >:) is becoming >☺ unintentionally, ruining the emoji's feeling 
So an angry emoji would be nice too lol

Anyway yeah, Im aware that the emojies are made using unicode characters and mostly Japanese hiragana/katakana symbols so I don't expect even 2 of these to be even possible but I just wanted to share some ideas anyway!

**Comment by CenizaRey** [comment]
The ascii emojis plugin is soon to be replaced by superior PNG emojis based on the resource pack. Closing!
