### ISSUE TITLE
[GTS] QOL change

### ISSUE THREAD

**Issue by Deathnight7976** [NebulaMC-GG/Suggestions#136]
Currently the minimum price on GTS is set to 2500, meaning to get to a nice number like say 35000, or 40000. I have to hit either -100/+100 GUI 5 times. This is annoying. I ask for either a +500/-500 option or just to set the minimum price to 3000. 

A custom +/- Would also be beneficial _**if possible**_ 
ex: a gui window set to whatever the user saves and does +/- 7976

**Comment by CenizaRey** [comment]
Minimum GTS price set to 3000 pending next restart. Thanks for the suggestion! Closing
