### ISSUE TITLE
Content Creator

### ISSUE THREAD

**Issue by Se7nCsD** [NebulaMC-GG/Suggestions#137]
Add either "Content Creator" or "Streamer" "Youtube" "Twitch" Ranks for people who post/stream on the server at least 1 day a week. maybe minimum followage is 100 or not any minimum

**Comment by CenizaRey** [comment]
We don't hand out special treatment to people who just happen to have a content creation platform. We feel it's unnecessary to stroke the egos of people who do by giving them something that sets them apart from the average player. While we appreciate them taking an interest and enjoying our server, the issue with it is there could be a million and one special cases and exceptions that will make handing out this rank unfeasible. Thanks for the suggestion! Closing
