### ISSUE TITLE
"Server to discord and discord to server" as staff only

### ISSUE THREAD

**Issue by dvos1998** [NebulaMC-GG/Suggestions#143]
As what has been said in staff channel, the purpose of the channel is for resolving issues and such via discord. imo a regular player should not be needed to help with that.

Also from what I understood from someone else, they don't like it that people can now read things back whenever they want, what has been said in the server chat (an example they gave is that they are oke with saying something to the people that are online in the server at that moment, but not that more than 1000 can read everything back what has been said whenever they want).
And for the point that you can go to a private discord or vc for that. Not everyone has discord or cant get on discord (just like the point that if someone has an issue and some are not always able to get to discord).

**Comment by CenizaRey** [comment]
At no point was an official statement made describing the purpose of the Server Bridge channels as something "for resolving issues". If we intended them to be staff-only channels, they would _be_ staff-only channels. The purpose of the Discord bridge is to enhance the experience of the playerbase, to allow them to communicate with their friends and chat with the ingame community while they can't get on the server.

As for the fact anything said in public chat can now be read back - GOOD. You cannot expect privacy for _anything_ you say in the Public Chat, and that was true before we had the server bridge. If you're worried about what you say being referred back to later, don't say it. We are in favour of a "nothing to hide, nothing to fear" attitude towards this topic. If you don't want others to refer back to what you have said, don't say it in public chat. Use /msg ingame if you want to avoid this, or perhaps DM them on Discord. 

Closing.
