### ISSUE TITLE
[Pwarps] Limit 1 per player

### ISSUE THREAD

**Issue by Deathnight7976** [NebulaMC-GG/Suggestions#144]
I want more `/pwarp` slots, maybe you unlock the ability to purchase more as you progress through dexranks? or even donor ranks? 

Either way they cost 75k each to create and I know multiple people have spoken about how they wish to have either multiple shops or even `/pwarps` setup to farms/platforms/biomes etc. I think an additional few slots per player wouldn't be all that bad.

Maybe even have the cost per `/pwarp` created increase as you purchase more as not to flood the `/pwarp` gui with to many warps? But even now there separated into different categories.

**Comment by CenizaRey** [comment]
As of next restart, you should have a limit of 3 total pwarps. Thanks for the suggestion! Closing.
