### ISSUE TITLE
Chat tag addition

### ISSUE THREAD

**Issue by CaptainTCovenant** [NebulaMC-GG/Suggestions#145]
With the perm tags we have currently; Dex tag and staff tags being one. I suggest seeing if theres a way to add a hover feature like there was during Oblique, showing each perm role they have. So people who have multiple staff tags can see them all. 

Unsure if this is a possibility with the current plug in but it would be lovely to see come back!

**Comment by Chunkkss** [comment]
Tags have been added!

Thanks for the suggestion!
