### ISSUE TITLE
Missing shiny sprite

### ISSUE THREAD

**Issue by KoolBro24** [NebulaMC-GG/Suggestions#147]
Fairy type gigalith doesn't have a shiny form it's just the same thing. Maybe something like normal gigaliths color scheme would be cool as a shiny?
![image](https://user-images.githubusercontent.com/118433491/202402412-3846083f-bd63-4655-ade6-db83732f394c.png)

**Comment by Chunkkss** [comment]
This Photo includes the shiny form. It's a darker form of the original.

Thanks for the suggestion.
