### ISSUE TITLE
Add Sweets to the Evolution Item Shop

### ISSUE THREAD

**Issue by aetherresonant** [NebulaMC-GG/Suggestions#150]
Title. I am aware Love Sweets are craftable, but I was specifically looking for a Berry Sweet, and found it somewhat weird that Alcremie's evolution items aren't in the evolution item shop. It would be quite helpful if they were added.

**Comment by CenizaRey** [comment]
Well said! These have been added to the Evolution Item Shop for next restart. Thanks for the suggestion! Closing.
