### ISSUE TITLE
[Suggestion] Ultra Space Material Converter

### ISSUE THREAD

**Issue by BunkerMonk** [NebulaMC-GG/Suggestions#151]
So, it looks like the recipes for the Ultra Space materials are a little on the fritz or just not done yet. You can not turn Ultra Space Stone into walls for instance, nor can you change logs to planks. At least according to JEI. As such may we have a temporary shop that sells the missing blocks or perhaps an npc that can take the base material and craft the items for us?

**Comment by KittyKatzyn** [comment]
Sorry for the delay!  Thank you for the suggestion!

This issue is a Pixelmon issue and has been fixed in Pixelmon for the next release (v9.1.1), BUT I've also ported over the recipes from that to our server's datapack so we'll get the recipes a bit early!
