### ISSUE TITLE
[Vanha] Adventure map apartments for players?

### ISSUE THREAD

**Issue by skateboardkid97** [NebulaMC-GG/Suggestions#152]
So as a builder I'd love to work on this project personally. However, how would this work for players/restrictions with claims? I'm unsure of the logistics but I'd love for it to happen, as some people may want to live on the adventure map rather than the wilderness map. Life through Vanha should be possible.

**Comment by CenizaRey** [comment]
There simply isn't enough space on the adventure map to make this viable for everyone without giant ugly apartment blocks. Vanha's cities are already very large, and adding more to them will make the map feel more like a collection of cities with nothing inbetween. Thanks for the suggestion! Closing
