### ISSUE TITLE
Increase the pages of the PC

### ISSUE THREAD

**Issue by EzelBerbier** [NebulaMC-GG/Suggestions#153]
Im a collector, and after reaching 100% there are some stuff that i wanted to do as a new objetives like do a living shiny dex, hunt all the special texture pokes, etc, but the pages of the PC are not enough if we thing in the new features coming (Vanha Pokes, Gen 9, new palette pokes...). And we need to include some extra free space for Synchronize Abras (if ur into competitive/breeding they are so useful), another one for Dittos with differente natures, really helpful when you are breeding (without thinking in the IVs), few pages for breeding stuff (HA pokes, Eggs, perfect parents...), a few boxes for perfect competitive pokes that breeded or u sell for other players, and extra pages for repeated legendaries, UB, shinies, alpha pokes, special texture pokes and pokes that ur breeding and u wanna sell. And we can include a new page for unown abedecary, because is something fun to do.

I did some maths with Excel and this is the result: 
![imagen_2022-11-28_071740504](https://user-images.githubusercontent.com/108286828/204207168-b5ff60c0-63bc-4cf7-9ca5-41881fed9fa4.png)

That picture shows the amount of pages you will use if u are interesting in do collection, that is part of the features of Pokémon games after all, and in this picture wasn't included differente forms that some pokémon have (Vivillon, Wormadan, Sawnsbuck, Alcremie, Florges...) and pokes with sexual dismorphism like Pyroar, Hippowdon, etc. That if ur are a collector is rare to avoid that stuff, mostly if u are doing shiny hunt. Painful? Yeah, but its part of the fun. 

If we reduce boxes with the stuff named at the begining (Dittos, Abras, Unown, Egg's page, HA poke page, Perfect Parents Page) we have left 10 pages for competitive pokes that u breeded or u bought and you are gonna use for gyms/battle other players/tournaments, shinies/UB/Legendaries/Special texture pokes that u would sell. 

In those 10 pages were not included the limited special texture pokes (Viral, Halloween, Autumn), and we need to think the new stuff the server and Pixelmon will include in the future, reducing even more the pages u will have free. However, i think part of the issue is because the PC is old, needs a rebrand that expand the slot per page, include more functionalities and other stuff that could make it much better than it is, but i don't have any idea if the Pixelmon devs have something in mind with that in future pixelmon updates, so if we are gonna focus in what we have, increase the PC pages will be awesome. 

So, and to resume, i think increase the PC pages to 80 is a really amount of pages (16*30 = 480 slots) and will be enough for a really long time.

**Comment by CenizaRey** [comment]
The problem with this is the PC stores a huge amount of data. It has to store all the information about each individual pokemon one by one, and all of this data is loaded each time you open the PC, causing lag. 

Increasing the PC size by such a massive amount is going to worsen this problem by quite a significant margin. We may reevaluate this when Gen 9 brings more species to capture, but for now, it’s not worth it to risk server and client performance quality just so a few collectors can have every vivillon.

Closing for now
