### ISSUE TITLE
[Statues] With addition of new world gen, statues should be accessible to players.

### ISSUE THREAD

**Issue by skateboardkid97** [NebulaMC-GG/Suggestions#154]
I'll summarize what I mean in the title, of course!

With the new update, there's statues everywhere and no one really gets any. It's a bit of a sad sight because everyone will ask how you get it to realize it's a perm that they cannot even have. 
Considering a house in a village in the woods can have 4-5 statues, and the village itself as decoration can have 5-10 statues, why would builders be unable to give people statues? 
Lag of course is a valid and valuable concern, and I'd say limit each player to 8 statues per household/claim. Like...an entire area limited to 8.

I, of course, know that statue implements aren't in place anytime soon especially with all the bugs and errors as a bug juicer. But as builder I would be completely fine managing the statues there. Maybe there could be a 'statue manager'? Sounds a bit dumb but it could work, recording where statues are on non-builder players and keep them in a little record section.

Sounds too complicated, honestly. But I would be utmost fine working with that. I just want the little guys who don't pay for anything to have something nice.

**Comment by Chunkkss** [comment]
Poke Displays are now purchasable for $20,000.

Thanks for the suggestion!
