### ISSUE TITLE
Berry harvest improvement

### ISSUE THREAD

**Issue by CptTCovenant** [NebulaMC-GG/Suggestions#157]
Was talking with a few other players that mass harvest berries for various stuff like making balls or gems for their shop and how slow berry harvesting is was a constant topic brought up. Harvesting berries/apricorns 1 by 1 for hours is tedious and boring I'm sure we can all agree. Thus I thought adding a custom enchant OR tool would be something interesting to add, more towards the farming community. 
What the tool / enchant would do: 
> Harvest berries in a 3x3 area, - this would cut harvest time drastically and give players more time for other activities. 

Tool idea: 
> A Sickle - pretty self explanatory. 
Crafted like a Hoe, but the top stick would be an Iron ingot. 

Enchant idea: 
> Harvester 1 - collects in a 1x2(direction the user is facing)  
> Harvester 2  - collects in a 3x3
Obtained by enchanting a book/enchanting a Hoe(and or sickle)

**Comment by CenizaRey** [comment]
Custom enchantments compatible with the Pixelmon mod is impossible with our current facilities, and making it possible is, relatively speaking, a poor use of our developer's time when they could be coding something far more useful and exciting. While this is a good idea, it is perhaps better to recommend it directly to Pixelmon. Closing
