### ISSUE TITLE
[Server Chats] A chat for Hub?

### ISSUE THREAD

**Issue by skateboardkid97** [NebulaMC-GG/Suggestions#158]
In the discord there's chats for every server. I think it'd be nice/helpful to have one for hub, since a lot of people join and might ask questions or be struggling to join the server. If this is just kind of not really a niche/wanted, we should have a thing signalling for people struggling to join to join the discord in the hub area.

**Comment by CenizaRey** [comment]
We feel this is unnecessary at this time. Thanks for the suggestion! Closing
