### ISSUE TITLE
Oblique style Questing?

### ISSUE THREAD

**Issue by Ayvorii** [NebulaMC-GG/Suggestions#163]
I don't know if anyone else asked for this, but it was one of my favorite things on the old version of the server and I haven't seen anything on it coming back or not, idk I just couldn't find any info so I was curious, thank you for your time.

**Comment by CenizaRey** [comment]
All of our quests were lost in the transition to 1.16, with no way of recovering them. We have been slowly building them back up, but learning a new quest building plugin and finding the manpower takes a huge amount of time. Rest assured, quests will be returning as soon as possible

**Comment by Ayvorii** [comment]
That makes sense, thank you!
