### ISSUE TITLE
Rank tags

### ISSUE THREAD

**Issue by EzelBerbier** [NebulaMC-GG/Suggestions#165]
Due to u can't switch between ranks, and we don't know (at least players) if that will be possible in the future, will be nice add Rank Tags (including Legacy tag), so in case u are part of the staff ore u paid for one of the ranks of the store, u will be able to show to others u achieved that maching the colors of the rank (master with purple, origin with red, legacy with that white purple idk which color is that, but u know what i mean).

It's not maybe the best solution, but could satisface the player at least before switch ranks turns into a possibility (or not, but it's something).

**Comment by CenizaRey** [comment]
Great idea!
