### ISSUE TITLE
Genesect Drives addition

### ISSUE THREAD

**Issue by EzelBerbier** [NebulaMC-GG/Suggestions#168]
As the same way N-Lunarizer and S-Solarizer was added to the market to let people buy it and don't force players to hunt Necrozma till the RNG decides to give them a Necrozma holding one, the held items of Genesect would be added to.

The Drives only change the type of the move Techno Blast, have some intereset in competitive but has a 25% chance for a Genesect to hold one of those, so you are forced to hunt (at least) 4 genesect and pray for obtain all of them in the first try, but we know RNG is not than merciful so you will be forced to hunt much more than that, something rough and tedious, and hunt a legendary is enough challenge by itself, mostly with the amount of playerbase that have the community. 

So, and to conclude, add the four drives into the market will help people that want genesect to use it, won't be forced to hunt even more. 

I forgot there was a Market Megathread, sorry in advance. So i suggest about 10k for the drives.

**Comment by CenizaRey** [comment]
Added as of next restart. Thanks for the suggestion! Closing
