### ISSUE TITLE
AFK Rule

### ISSUE THREAD

**Issue by zTsuno** [NebulaMC-GG/Suggestions#169]
Recently I have heard that afk pooling is allowed, but it is still assigned to rule #5 in /rules.
![image](https://user-images.githubusercontent.com/106882836/210465904-7b8111b9-6b0a-4e38-b51d-8c26ee0f0e7f.png)

Can we remove that for moderation sake please?

**Comment by Chunkkss** [comment]
This has been removed. 

Thanks for the suggestion!
