### ISSUE TITLE
Increase or change heracross time spawn

### ISSUE THREAD

**Issue by EzelBerbier** [NebulaMC-GG/Suggestions#175]
Due to headbutt is broken again, and we don't know if next updates external moves will be broken again, hunt heracross is a pain in the ass if u need or you are looking for one, due to have 5.0 rarity spawning only during dawn/dusk in biomes with a enough pool of fight and bug pokémons, making spawn one a nightmare even with strong lures. 

So I suggest two possible solutions: increase the default rarity to make it less painful or change the time spawn to day or night in the same biomes, so even if he have the default rarity, u have more chances and u will suffer less, even if that takes u time and effort.

**Comment by CenizaRey** [comment]
Changed as of next restart. Thanks for the suggestion! Closing
