### ISSUE TITLE
[END] Accesible raids and a healer area in the main island

### ISSUE THREAD

**Issue by EzelBerbier** [NebulaMC-GG/Suggestions#180]
Do raids it's easier thanks to US, and we only can expect more biomes full of raids to be able to hunt different raids, and hunt HAs more comfortable, but in the END it's pretty hard, there are much more less raids and they are dispersed in the whold End, make it a very mess, so would be nice add raids around the new island, so people would be able to do end raids easier and hunt HAs there better. I think would increase the players going to the end, becuase right now it's a died dimension that people only go for catch few pokes for dex, for hunts or bingo.

Furthermore, would be nice to add few healers/PC in the main island, so people that does not have any paid rank, will be able to heal there or check some stuff in the PC, due to it's impossible do it by yourself for be claimed, and was something that was there in the first End, getting eliminated in the first end reset.

**Comment by Chunkkss** [comment]
This is a good idea, however:

There's already a healer and PC at the end. I think it would be beneficial to add a small platform where the PC and Healer are at the end with a Raid, PC, Healer, and a Trading machine as well. Wouldn't take away from anything, but add to player experience in the End.

**Comment by Chunkkss** [comment]
This has been completed for each server. 

Thanks for the suggestion!
