### ISSUE TITLE
Convert market into a forum channel

### ISSUE THREAD

**Issue by WisconsinWinters** [NebulaMC-GG/Suggestions#183]
With the rise of GTS and other new methods of players being able to sell items, I believe that #market will be better off being converted into a forum channel. 

Players can be free to advertise their shop or wares in one single post, and be able to tag it with tags such as "items", "pokeballs", or "legendary pokemon", etc. Tags can also be split into the servers as well, and whether or not the person is buying or selling

Some basic ground rules suggestions to the subforum would be "No self-bumping more than once every 24 hours", to reduce the amount of new staff overhead needed to manage the subforum.

**Comment by Chunkkss** [comment]
I like the idea, however this makes PWARPS essentially useless. We love to promote anything that is In-Game as that's where the experience lies.

Market is good where it's at, as you can promote your shop easily while still listing all the items you sell.
