### ISSUE TITLE
New players getting starters

### ISSUE THREAD

**Issue by HealthyCoyote32** [NebulaMC-GG/Suggestions#186]
I think that the people who have played before the shiny starters should get a shiny starter of their choice or some kind of random shiny that could be legendary/mythical

**Comment by Chunkkss** [comment]
I don't think this would be very fair, as players that have joined before the shiny starters have had plenty of time / events to gain Shiny and Legendary Pokemon. 

This is something that was spoken about, and refunds for this would not be happening. If you would like a shiny starter, you are allowed to restart your progress on your server. This would wipe your entire Dex, PC, and Party though.

**Comment by CenizaRey** [comment]
Chunks said it best, closing
