### ISSUE TITLE
Poll for new mega

### ISSUE THREAD

**Issue by AftonsHell** [NebulaMC-GG/Suggestions#191]

**Comment by AftonsHell** [comment]
I’m thinking that for the next server update we should take at least 4 mons that don’t have a mega yet (like ones that aren’t really used, ones that deserve a mega, and g-max Pokémon that haven’t gotten a mega yet) and give them a mega evolution. Like run a poll for the randomly selected 4 mons and ask the server to vote on who should be added in the next update.

**Comment by Chunkkss** [comment]
Cen mentioned previously that there wont be a poll for the next mega or custom Pokemon due to the time consuming and expensive process.

Appreciate the suggestion! Thanks
