### ISSUE TITLE
Resetting End/Nether

### ISSUE THREAD

**Issue by NotPond** [NebulaMC-GG/Suggestions#198]
There is nothing left to find in generated structures especially in the End and the Nether, making it incredibly difficult to find different items required for getting certain legendary pokemon. So, I was hoping these two dimensions were going to get reset soon.

**Comment by Rasgnarok** [comment]
Accepted, the Nether, End and Ultraspace will be set to reset within the next 30 days. Stay tuned in our discord.gg/nebulamc
