### ISSUE TITLE
I want to add a feature to this server

### ISSUE THREAD

**Issue by buddybud7** [NebulaMC-GG/Suggestions#200]
As a representative of Panda Industries I want to initiate the idea of adding a counsellor lawyer before couples in marriage can divorce. Another thing I want to add is if someone is accused of plagiarism of someone's idea then we can initiate a courtroom on each server. I know this sounds ridiculous but I feel as the CEO and Representative of Panda Industries we could add these features to settle arguments.

**Comment by CenizaRey** [comment]
Unfortunately, our tracker is mostly for suggestions that aren't rooted in inside jokes or roleplaying. It would be kinda funky to implement medieval marriage laws into Nebula, additionally. You are more than welcome to build a courtroom on each server, but most arguments can be settled with just a few messages in chat. Thanks for the suggestion! Closing
