### ISSUE TITLE
Bingo Gui Info

### ISSUE THREAD

**Issue by Centuron** [NebulaMC-GG/Suggestions#201]
Can we add back the book/ exclamation mark that used to show what you would get for doing the bingo?
As of right now, newer players have no way of knowing what they can get by doing the bingo and I think people are basically ignoring this feature since they don't know if it is worth their time or now.

**Comment by KittyKatzyn** [comment]
This has been reinstated!  There was an issue with the Bingo mod, which was recently fixed, so updating to the most recent version has brought back the Info book :D

The mod has been queued to be active on all servers (after being tested on Beta briefly) after each restarts.  

Thanks for the suggestion! Closing!
