### ISSUE TITLE
Battle Tower Economy Issues

### ISSUE THREAD

**Issue by Jordanjday** [NebulaMC-GG/Suggestions#213]
Server: Titan
IGN: EmperorJD 
Nickname: Jordan

Hello Dev Team,

I was hoping that something could be done about the Reward from the BattleTower. I think that there is an issue with the tower having no cooldown. Right now it feels like the price of legendaries is inflating quite quickly, while the rest of the items are not increasing. This is causing not only legendaries to be extrordinarily expensive, but it feels like most other items are extremely inexpensive, causing a supply issue, because the amount of money that people have makes it easy to just pick up as many of any item they like without much effort, leading to an over scarcity of items, with whole days going by without an item coming up for sale anywhere. I am sure that the battle tower Is not the only issue, but it does make things feel very trivial in terms of money/

Cheers,

Jordan

**Comment by CenizaRey** [comment]
Dealt with, thanks for the report! Closing
