### ISSUE TITLE
Error with Crate Coin Rewards

### ISSUE THREAD

**Issue by Dracorexion** [NebulaMC-GG/Suggestions#237]
![image](https://github.com/NebulaMC-GG/Suggestions/assets/134461703/ee0173fa-a9b2-4b5f-be03-0b32fe541607)
As pictured above, when someone wins money from a crate, it seems to glitch with the hexcode. This is the only example I've seen so far, though it's possible it's affecting other money rewards and not just 10k

**Comment by WisconsinWinters** [comment]
fixed, clsing
