### ISSUE TITLE
Silver Ingots and Tumblestones Pokemon drops

### ISSUE THREAD

**Issue by Shika-The-Deer** [NebulaMC-GG/Suggestions#57]
I created a list of Pokemon that are intended to drop silver ingots and tumblestones by the mod, but do not/may not drop them on the server due to outdated drop files (Told to put as a suggestion by Faty to be looked at by Cen later)

Silver Ingots:
Skarmory
Bronzor
Bronzong
Magnezone

Tumblestones (Parenthesis indicate what type of tumblestone, otherwise default):
Machop line 
Kanto Geodude line
Onix (Black)
Rhyhorn line (Black)
Magikarp
Gyarados (Sky)
Sudowoodo (Black)
Mantine line (Sky)
Chimecho line (Sky)
Skorupi line (Black)
Croagunk line

**Comment by CenizaRey** [comment]
Fixed for next reset, thank you Shika!
