### ISSUE TITLE
Ball changing item preview video for nebulas youtube channel

### ISSUE THREAD

**Issue by Qaz1337** [NebulaMC-GG/Suggestions#58]
I was trying to decide what ball to use my coupon on and I had no clue what the balls looked like. Would be easy to record and good help for players unsure what looks good ing.

**Comment by Rasgnarok** [comment]
What do you mean? You already know what the pokeballs look like because they are on Pixelmon's wiki, https://pixelmonmod.com/wiki/Poke_Balls#Types
