### ISSUE TITLE
Multiple Suggestions

### ISSUE THREAD

**Issue by Se7nCsD** [NebulaMC-GG/Suggestions#60]
Readd Pokemon Caught on Tab Menu
Readd Perms for Discord Supporter

**Comment by Rasgnarok** [comment]
Worth making separate tickets please, especially because both deserved to be fleshed out.
1. Do you want a full profile? sidetab? full TAB? more parameters like rank, money, etc?
2. Do you want a channel for supporters? just colours? choice colours? etc
