### ISSUE TITLE
[Suggestion] Upgrade the Free Disguise Pack if it reappears in the future.

### ISSUE THREAD

**Issue by BunkerMonk** [NebulaMC-GG/Suggestions#68]
I would like to request that 1 (maybe 2) pokemon get added to the free disguise pack if it returns when pokedisguises is ready to go. The mons in question would be:

Quagsire 
(Maybe Whooper)

The reason: It is the server mascot. Also, it would allow the original version of Where's Wooper to return which is where players could hide themselves as pokemon and the seekers would hunt them down.

**Comment by CenizaRey** [comment]
We have no plans to reintroduce this, sadly. Thanks for the suggestion! Closing for now
