### ISSUE TITLE
Vote Crate PokeBalls

### ISSUE THREAD

**Issue by Khrisstias** [NebulaMC-GG/Suggestions#69]
currently you can get 10 pokeballs from the crate, when other balls you get 16 of, it would be nice to see it get bumped up to 16
![2022-06-25_22 51 28](https://user-images.githubusercontent.com/37944220/175798662-2c56eadd-4268-402c-af3a-a19912835ff2.png)

**Comment by HackuJacku** [comment]
This change has been implemented as part of our crates update, thank you for the suggestion :)
