### ISSUE TITLE
Bring back /mstrade

### ISSUE THREAD

**Issue by itanomaly** [NebulaMC-GG/Suggestions#70]
As the title says, bring back a command that'll accept one megastone and replace it with another random one. It used to have 30 min cooldown, and I think it's a good addition to the server, because everyone hates getting stuck with bad luck, having like 3~4 of the same megastone.

**Comment by Rasgnarok** [comment]
Since we now have megastone crates, adding /mstrade would defeat the purpose of megastone crate keys. Closing.
