### ISSUE TITLE
Daily Activity IV Voucher.

### ISSUE THREAD

**Issue by BunkerMonk** [NebulaMC-GG/Suggestions#75]
Suggestion in Full:
Please let us have a daily task that upon completion rewards us with a +1 / -1 IV Voucher that makes our pokemon sterile. 

Reason for this change:
1. There are many pokemon in Nebula that lose something if they are breed or just flat out can not be breed. This includes pokemon with story significance (Not an issue at this time with no quests), our starters (losing the chosen one ribbon is sad), shiny pokemon, and finally that legend that you got lucky to spawn on you.

2. These vouchers have recently been nerfed hard with them now sterilizing your pokemon to never have babies. As such they shouldn't keep the same rarity that they held in the past.

3.This will provide a constant activity to the players as even a single pokemon will take on average 93 vouchers to max out. 

4. If you are wondering why I included the ability to drop a stat point. It's for hidden power, foul play protection, and trick room users who need either a set stat or a low stat in IVs.

**Comment by Rasgnarok** [comment]
https://github.com/NebulaMC-GG/Suggestions/issues/72
