### ISSUE TITLE
Add GS Ball to Mythical /hunts Rewards

### ISSUE THREAD

**Issue by Smith-sonite** [NebulaMC-GG/Suggestions#78]
I think the title says it all. I left this comment in the #suggestions channel on discord, but I figured I'd put it here just in case it got lost. You can see quite a few endorsements for the idea as well!
<img width="647" alt="Screen Shot 2022-07-14 at 2 24 17 PM" src="https://user-images.githubusercontent.com/107899014/179088726-2959f5c1-8c14-4d47-b1da-223642d64409.png">

**Comment by Rasgnarok** [comment]
We won't be adding this as the GS Ball immediately summons Celebi. The Red Chain still requires you to have the Lustrous/Griseous/Adamant items, and therefore isn't as comparable. GS Ball is right now on /bingo, however.
