### ISSUE TITLE
Custom Titles

### ISSUE THREAD

**Issue by PenginKami** [NebulaMC-GG/Suggestions#82]
Cosmetic titles unlock for doing certain things in game, with others obtained via cosmetic crate. You'd be able to choose which title you'd like to specifically display in a GUI out of the ones you own.

I haven't explained what I meant by title so ill do that now:

Instead of being
[OMEN] PenguinOfLife
You could sub out omen for a title such as

[☆] PenguinOfLife
[Legendary] Thangtaolao
[IBuyTooManyCrates]
Stridiie

The existing rank titles and dexrank titles can be added to this system too, so you can swap those back in if you like a certain dexrank title more than another 

![image](https://user-images.githubusercontent.com/96862959/186023335-aa83b6d9-c72e-4fa0-9194-3a3c52eed349.png)
Here is what the GUI would look like. Upon selecting a title, it'd remove the other title. Titles like [OMEN] and the dexrank ones would be put into this list, so you as a player can choose which title you prefer.
Explaining the GUI: each red stained glass would be a different title (that isn't unlocked) It'd display the name of the title and a hint of how to obtain it.

For example, a title like [Rich] (w.i.p name) would have a hint like
"Purchase the most expensive item in the market!" (The pikamug)
They could become goals for players.

There's already a system in place to show someone's Official rank when hovering over as well, so less confusion.
![image](https://user-images.githubusercontent.com/96862959/186023550-2c012d81-7b06-4116-9f8a-db4a4e2a7396.png)

**Comment by CenizaRey** [comment]
I really like this idea, unlockable titles would be super fun. Would need to format it in a way that doesn't make ingame ranks appear confusing, maybe custom login/logout messages could be used

**Comment by CenizaRey** [comment]
As was revealed a couple of days ago, this is currently in development. Keep your eyes peeled for updates!
