### ISSUE TITLE
Alias for one-time staff chat messages

### ISSUE THREAD

**Issue by Smith-sonite** [NebulaMC-GG/Suggestions#84]
Would be nice to have an alias for single staff chat messages instead of typing out /staffmsg (message). It was /sc or /a on Oblique.

Note: Cen has already tried and believes this is likely not possible with the current plugin.

**Comment by Vavalur** [comment]
To my knowledge this should be 100% possible, considering cmi has a built in alias creator. while /sc or /a may not work, there should be some suitable alias that can be used. Maybe /sm or /smsg?

**Comment by CenizaRey** [comment]
I have discussed this numerous times with staff members, including Hacko, and concluded that it is not possible. Trying to alias /staffmsg only attempts to adjust the toggle, not the one-time command. 

CMI does have a built-in alias creator, but it has its limitations. This is one of them. Closing for now.
