### ISSUE TITLE
A Place for Move Tutors

### ISSUE THREAD

**Issue by AvalinDragon** [NebulaMC-GG/Suggestions#86]
I think it would be a nice idea to have a place where you can access different move tutors to get moves on pokemon that would need one. It would save time hunting for the right move tutor in the wild, plus I haven't actually seen any spawn. A pricing system could be added to this as well, such as buying tokens for move tutors at a certain price or something like that.

**Comment by CenizaRey** [comment]
A series of great ideas! Thankfully all of the above is already prepared and waiting on the adventure map. There will be an announcement with all of the move tutor's locations and the moves they teach. Their tokens (heart scales) are already priced too, they'll be added to /warp market NPCs shortly. The adventure map releases very soon! Closing for now.
