### ISSUE TITLE
[Suggestion]Alteration to the Bingo Rewards

### ISSUE THREAD

**Issue by BunkerMonk** [NebulaMC-GG/Suggestions#88]
Suggestion: Either remove unbreed from both rewards OR buff the shiny and HA pokemon to gamefreaks standard 3 guaranteed IV for good stuff. 

Reasons: 
- With Unbreed on these prizes they are truly worth less then dirt. 
- I can farm for an HA pokemon that is breedable of my choice in probably a quarter of the time it takes to complete a full Bingo. 
- Hell, I have grinded for a shiny of my choice in a quarter of the time. 
- Okay, this reason might be off the mark so it is last on the list. But you guys do know that 1 single perfect IV is worthless in the grand scheme of things right? Each IV only gives the pokemon 1 single stat point. At lv 100, most pokemon several hundred of these. You have to get mega unlucky to even hit 0 IVs so 99.9% of the time, the perfect IV isnt even giving your pokemon a 10% power boost. Its most likely 4-6%. Genuinely, not worth that much effort. This is why the first step of breeding a pokemon is to fix the natures of them. A positive nature is a straight up 10% upgrade to the stat for a worthless one no questions asked. 

Thus the current rewards read as such:
You give me 6 hours of your day and I'll give you a shiny mon that has 1 stat (could even be a worthless stat for them) a 4-6% power boost.

**Comment by CenizaRey** [comment]
I decided to meet you halfway by guaranteeing 2 perfect IVs instead of 1. Closing for now!
