### ISSUE TITLE
Temporally fix for Toxel evolutions

### ISSUE THREAD

**Issue by Menno165** [NebulaMC-GG/Suggestions#91]
Toxel is unable to evolve into its amped form if it has the natures Jolly and Hasty.
I assume it is because this is not in the sjon data file. Would it be possible to add this until pixelmon fixes it?

**Comment by KittyKatzyn** [comment]
This appears to have already been fixed by Pixelmon, yay!

Closing; thank you for your suggestion (and sorry we didn't get to it earlier)!
