### ISSUE TITLE
Re-dye colored blocks

### ISSUE THREAD

**Issue by Vavalur** [NebulaMC-GG/Suggestions#94]
Would be nice to convert colorful blocks between colors. 
Example: Red Wool to blue Wool or all colors back to white variant so they can then be recolored
Would be a lot of custom recipe set up, but I think it would be amazing for builders

**Comment by Malphir** [comment]
If this is to be looked into, I would recommend looking at 'Vanilla Tweaks' released by XisumaVoid and his team. They have a lot of different options available to select from on their site. One of which is universal dyeing, which matches this request.

https://vanillatweaks.net/picker/crafting-tweaks/

**Comment by fatyg5** [comment]
I will discuss this further with the admin team.

**Comment by CenizaRey** [comment]
This has been completed on a limited basis for next reboot. You will be able to 'clean' coloured blocks back into their white/base form for re-dying purposes in batches of 8. Thanks for the suggestion!
![terracotta](https://user-images.githubusercontent.com/42212238/188957992-954f97ad-994f-467e-bf45-9fc12c38cb2b.png)
![wool](https://user-images.githubusercontent.com/42212238/188957993-28176ec9-2f14-408e-ba7e-0a78bde8cbd3.png)
![concrete](https://user-images.githubusercontent.com/42212238/188957995-2fc91abb-48bc-43c9-ad5f-4040c80dc4d8.png)
![powder](https://user-images.githubusercontent.com/42212238/188957997-799f8e4f-fdd2-45d8-8cfb-8bdec58d8de2.png)
